### ISSUE TITLE
注意

### ISSUE THREAD

**Issue by feixueck** [puhaiyang/flowable-springboot#1]
看到这个例子的同学请注意 : 
作者之前用的springboot版本是 2.0.1.RELEASE
// 作者最新把项目升级到了 2.1.1 ,直接运行这个项目会报错 ,sql无法初始化 .
//如果需要正确运行 ,需要把springboot版本回退 .
好心提醒 .

**Comment by Alenfitz** [comment]
升级mysql驱动到8.x以上即可
